### PR TITLE
Fix package build

### PR DESCRIPTION
**Pull request by irikuo**
The final package built by webpack was wrong, including `module.export` in the beginning, so it couldn't be used in a third party project without webpack. This library should be as universal as possible, so it needs to be compiled as a UMD module.

In this PR `nvm` has been replaced with `nodenv` to improve the DX ;)

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
*If you're new, read the [guidelines]
(https://github.com/reevoo/guidelines/blob/master/pull_requests.md).*

Good code is **tested**, **designed for change**, **easy to understand**
and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [ ] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need
tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [ ] The code is well-designed and able to cope with change.
- [ ] The code is easy to understand.
- [ ] Tests cover happy and unhappy paths in the code.
- [ ] Tests are green on CI (or pulled/tested on your machine).

**Comment by davidsevcik** [comment]
I don't get this, how the uglification can make it work for projects without webpack? I thought that uglification just makes the code shorter but don't modify any behaviour??

**Comment by irikuo** [comment]
Actually you made me notice something. I checked again the minified file and it has the same problem as before. Basically it starts with `module.exports` and `module` is not defined in the browsers, so it can be used just with bundling tools (webpack or browserify) but not as a standalone thing. I will try to check when did the behaviour changed and why.

Thanks @davidsevcik !

**Comment by irikuo** [comment]
@davidsevcik I found this https://github.com/reevoo/reevoo-ping.js/commit/7c331bc9c31554c3507a8b1c72e1fd985a72a881 that is when `libraryTarget: 'commonjs2',` was added. Why do we need the module exposed like that, wasn't it working in `narnia` and `mark` before? I am thinking that maybe we need to generate two different files if we want to use it in different ways (directly in browser or imported as a module).

**Comment by irikuo** [comment]
It looks like if I remove the line `libraryTarget: 'commonjs2',` from the `webpack.config.js` file it works in Fast Response (that is what I was trying to do). But I can't find the PR that explains why we needed this in the first place, so I am not sure if it's safe enough to remove it.

**Comment by irikuo** [comment]
After thinking a lot about this I found that the problem of using this library in other sites is not related with the library itself, is related to how we use it. That's why in this PR we are going to compile the library again as a UMD module, to make it as universal as possible.

**Comment by davidsevcik** [comment]
LGTM

**Pull request merged**
